### ISSUE TITLE
not getting order confirmation mails after mollie install

### ISSUE THREAD

**Issue by christophepa** [mollie/OpenCart#120] opened 2018-12-02 08:25 UTC
Hi 

I Installed mollie OpenCart module (9.0) as it should be in my new Opencart (Versie 3.0.2.0). Installation went fine, all seemed ok, I was able to do test and live. But since installation of mollie my users do not get the order confirmation mail, and neither does the admin.

I've been testing a lot allready, been looking on tons of forums because mail issues seem to be widespread in Opencart, but still no result to my issue.
- all alerts enabled, extra mailadress added (does not get mail neither)
- marketing - mail: goes to client, no errors
- New client -> ok - both client and admin get mail
- review -> ok - mail goes to client and admin
- Used both php mail and smtp: both seem to work normally

I also get an error when selecting Belfius:

Fatal error: Class 'ControllerExtensionPaymentMollieBelfius' not found in ...........catalog/controller/extension/payment/mollie_belfius.php on line 4

PS: if I chose non-mollie payments, order mails do get send!

Is this something that can be fixed?

Thank you!
greets
Christophe

feel free to react in English or Dutch ;-)

**Comment by Charl13** [comment] 2018-12-04 16:36
Im experiencing the same issue in Opencart 3, order confirmation email not send after updating the mollie extension from v8.4.2 to v9.0.0. As a side note, I had to install vqmod in order to install mollie extension v9.0.0. I have been debugging this issue for some hours already. Despite not having found the solution yet, Im close to finding the cause.

Opencart uses its [event system](https://github.com/opencart/opencart/wiki/Events-System) to tigger certain actions. Sending an order confirmation email is such an action. The event that triggers this action is `catalog/model/checkout/order/addOrderHistory/before`. It seems that this event is not begin triggered and thats why the email is not begin send.

In v8.4.2 in the controller `ControllerExtensionPaymentMollieBase` [at line 115](https://github.com/mollie/OpenCart/blob/1ad19b13e2156a6203a46483ecc5728128849eeb/catalog/controller/extension/payment/mollie/base.php#L115) the model `checkout/order` is loaded using `$this->load->model('checkout/order')`. This returns an [Opencart proxy](https://github.com/opencart/opencart/blob/master/upload/system/engine/proxy.php). The proxy intercepts method calls and fires actions connected to it.

In version v9.0.0 this is changed. In the controller `ControllerPaymentMollieBase` [at line 117](https://github.com/mollie/OpenCart/blob/master/catalog/controller/payment/mollie/base.php#L117) the model is loaded using `Util::load()->model("checkout/order")`. This doesn't return a proxy, it returns the plain model. Without the proxy begin used actions are not triggered which means that the order confirmation email is not send.

**Comment by TiaID** [comment] 2018-12-14 10:37
I had the very same issue. Im back on OC 2.1.0.2 again,

Hope there will be a fix soon.

**Comment by tacovansambeek** [comment] 2019-01-08 10:45
this is fixed in 9.0.2

**Closed** 2019-01-10 15:39 UTC
